"""pylcm twin of the `dcegm` package's IJRS consumption-retirement toy model.

Mirrors the model documented in `tests/data/dcegm_reference/generate_fixtures.py`
so its solution is comparable to the fixture CSV generated by the independent
`dcegm` implementation:

- CRRA utility `(c**(1 - rho) - 1) / (1 - rho)` minus work disutility `delta`;
  EV1 taste shocks on the work/retire choice (scale is a runtime param).
- Income is earned one period after working and indexed by the receiving
  period's age: the wealth transition uses the *current* work choice, which is
  exactly the `dcegm` lagged-choice timing.
- Retirement is absorbing (separate regime without the work action).
- The `dcegm` final period consumes everything but still draws the taste shock
  on the (income-less) work/retire choice. Its smoothed value has the closed
  form `crra(wealth) + scale * log(1 + exp(-delta / scale))` for an agent who
  was working, and `crra(wealth)` for a retiree — encoded as two terminal
  regimes.

Builders return the brute-force and DC-EGM spec variants of the same model.
Importable only once `lcm.taste_shocks` and `lcm.solvers` exist.
"""

import functools
from typing import Literal

import jax.numpy as jnp

from lcm import (
    AgeGrid,
    DiscreteGrid,
    IrregSpacedGrid,
    LinSpacedGrid,
    LogSpacedGrid,
    Model,
    categorical,
)
from lcm.regime import Regime as UserRegime
from lcm.solvers import DCEGM
from lcm.taste_shocks import ExtremeValueTasteShocks
from lcm.typing import (
    BoolND,
    ContinuousAction,
    ContinuousState,
    DiscreteAction,
    FloatND,
    ScalarInt,
)

MIN_AGE = 20
N_PERIODS = 10
LAST_ALIVE_AGE = MIN_AGE + N_PERIODS - 2  # 28; the final period is terminal

# The wealth grid must reach down to the consumption floor (0.001): the floor
# makes near-zero wealth reachable, and a grid that starts above it lets the
# brute solver's edge clamp make consuming down to the floor look good. CRRA
# value is sharply curved at low wealth, so the grid is geometric below 0.5,
# fine-stepped through the low fixture nodes (1, 2, 5), and 0.5-stepped above
# — every fixture wealth point (1, 2, 5, 10, 20, 35) sits exactly on a node.
_FLOOR_WEALTH_POINTS = tuple(0.001 * (0.5 / 0.001) ** (i / 120) for i in range(120))
_MID_WEALTH_POINTS = tuple(0.5 + 0.05 * i for i in range(90))
_TOP_WEALTH_POINTS = tuple(5.0 + 0.25 * i for i in range(181))
WEALTH_GRID = IrregSpacedGrid(
    points=_FLOOR_WEALTH_POINTS + _MID_WEALTH_POINTS + _TOP_WEALTH_POINTS
)
# Log spacing resolves the small optimal consumption of poor retirees; the
# lower end matches the consumption floor so the lowest wealth node keeps a
# feasible consumption choice.
CONSUMPTION_GRID = LogSpacedGrid(start=0.001, stop=50.0, n_points=400)
# Matches the `dcegm` run's exogenous savings grid exactly.
SAVINGS_GRID = LinSpacedGrid(start=0.0, stop=50.0, n_points=500)


@categorical(ordered=False)
class TwinRegimeId:
    working_life: ScalarInt
    retirement: ScalarInt
    done_from_working: ScalarInt
    done_retired: ScalarInt


@categorical(ordered=True)
class WorkChoice:
    work: ScalarInt
    retire: ScalarInt


def crra(consumption: FloatND, rho: float) -> FloatND:
    return (consumption ** (1.0 - rho) - 1.0) / (1.0 - rho)


def is_working(work_choice: DiscreteAction) -> BoolND:
    return work_choice == WorkChoice.work


def utility_working(
    consumption: ContinuousAction, is_working: BoolND, rho: float, delta: float
) -> FloatND:
    return crra(consumption, rho) - jnp.where(is_working, delta, 0.0)


def utility_retired(consumption: ContinuousAction, rho: float) -> FloatND:
    return crra(consumption, rho)


def utility_done_from_working(
    wealth: ContinuousState, rho: float, delta: float, taste_scale: float
) -> FloatND:
    """Smoothed consume-all value incl. the final-period choice taste shock."""
    return crra(wealth, rho) + taste_scale * jnp.log(
        1.0 + jnp.exp(-delta / taste_scale)
    )


def utility_done_retired(wealth: ContinuousState, rho: float) -> FloatND:
    return crra(wealth, rho)


def labor_income(
    is_working: BoolND,
    age: float,
    constant: float,
    exp_coeff: float,
    exp_squared: float,
) -> FloatND:
    """Income from working this period, paid next period at next period's age."""
    next_age = age + 1.0
    log_income = constant + exp_coeff * next_age + exp_squared * next_age**2
    return jnp.where(is_working, jnp.exp(log_income), 0.0)


def next_wealth(
    wealth: ContinuousState,
    consumption: ContinuousAction,
    labor_income: FloatND,
    interest_rate: float,
    floor: float,
) -> ContinuousState:
    return jnp.maximum(
        (1.0 + interest_rate) * (wealth - consumption) + labor_income, floor
    )


def resources(wealth: ContinuousState) -> FloatND:
    return wealth


def savings(resources: FloatND, consumption: ContinuousAction) -> FloatND:
    return resources - consumption


def next_wealth_from_savings(
    savings: FloatND,
    labor_income: FloatND,
    interest_rate: float,
    floor: float,
) -> ContinuousState:
    return jnp.maximum((1.0 + interest_rate) * savings + labor_income, floor)


def inverse_marginal_utility(marginal_continuation: FloatND, rho: float) -> FloatND:
    """Inverse of `u'(c) = c**(-rho)`."""
    return marginal_continuation ** (-1.0 / rho)


def borrowing_constraint(
    consumption: ContinuousAction, wealth: ContinuousState
) -> BoolND:
    return consumption <= wealth


def next_regime_from_working(work_choice: DiscreteAction, age: float) -> ScalarInt:
    last = age >= LAST_ALIVE_AGE
    retire = work_choice == WorkChoice.retire
    return jnp.where(
        last,
        jnp.where(retire, TwinRegimeId.done_retired, TwinRegimeId.done_from_working),
        jnp.where(retire, TwinRegimeId.retirement, TwinRegimeId.working_life),
    )


def next_regime_from_retirement(age: float) -> ScalarInt:
    return jnp.where(
        age >= LAST_ALIVE_AGE, TwinRegimeId.done_retired, TwinRegimeId.retirement
    )


done_from_working = UserRegime(
    transition=None,
    states={"wealth": WEALTH_GRID},
    functions={"utility": utility_done_from_working},
)

done_retired = UserRegime(
    transition=None,
    states={"wealth": WEALTH_GRID},
    functions={"utility": utility_done_retired},
)


DCEGM_SOLVER = DCEGM(
    continuous_state="wealth",
    continuous_action="consumption",
    resources="resources",
    post_decision_function="savings",
    savings_grid=SAVINGS_GRID,
)


def _working_life(solver: Literal["brute_force", "dcegm"]) -> UserRegime:
    brute = UserRegime(
        transition=next_regime_from_working,
        states={"wealth": WEALTH_GRID},
        actions={
            "work_choice": DiscreteGrid(WorkChoice),
            "consumption": CONSUMPTION_GRID,
        },
        taste_shocks=ExtremeValueTasteShocks(),
        active=lambda age: age <= LAST_ALIVE_AGE,
        state_transitions={"wealth": next_wealth},
        constraints={"borrowing_constraint": borrowing_constraint},
        functions={
            "utility": utility_working,
            "is_working": is_working,
            "labor_income": labor_income,
        },
    )
    if solver == "brute_force":
        return brute
    return brute.replace(
        state_transitions={"wealth": next_wealth_from_savings},
        constraints={},
        functions={
            "utility": utility_working,
            "is_working": is_working,
            "labor_income": labor_income,
            "resources": resources,
            "savings": savings,
            "inverse_marginal_utility": inverse_marginal_utility,
        },
        solver=DCEGM_SOLVER,
    )


def _retirement(solver: Literal["brute_force", "dcegm"]) -> UserRegime:
    brute = UserRegime(
        transition=next_regime_from_retirement,
        states={"wealth": WEALTH_GRID},
        actions={"consumption": CONSUMPTION_GRID},
        active=lambda age: age <= LAST_ALIVE_AGE,
        state_transitions={"wealth": next_wealth},
        constraints={"borrowing_constraint": borrowing_constraint},
        functions={"utility": utility_retired},
    )
    if solver == "brute_force":
        return brute
    return brute.replace(
        state_transitions={"wealth": next_wealth_from_savings},
        constraints={},
        functions={
            "utility": utility_retired,
            "resources": resources,
            "savings": savings,
            "inverse_marginal_utility": inverse_marginal_utility,
        },
        solver=DCEGM_SOLVER,
    )


@functools.cache
def get_model(solver: Literal["brute_force", "dcegm"]) -> Model:
    """Build the twin model for the requested solver variant."""
    return Model(
        regimes={
            "working_life": _working_life(solver),
            "retirement": _retirement(solver),
            "done_from_working": done_from_working,
            "done_retired": done_retired,
        },
        ages=AgeGrid(start=MIN_AGE, stop=MIN_AGE + N_PERIODS - 1, step="Y"),
        regime_id_class=TwinRegimeId,
    )


def get_params(*, taste_shock_scale: float = 0.2) -> dict:
    """Params matching the fixture run in `tests/data/dcegm_reference/`."""
    return {
        "discount_factor": 0.95,
        "interest_rate": 0.05,
        "rho": 1.95,
        "delta": 0.35,
        "constant": 0.75,
        "exp_coeff": 0.04,
        "exp_squared": -0.0002,
        "floor": 0.001,
        "done_from_working": {"utility": {"taste_scale": taste_shock_scale}},
        "working_life": {"taste_shocks": {"scale": taste_shock_scale}},
        # Retired agents earn nothing; `labor_income` is a free leaf of the
        # retirement regime's wealth transition.
        "retirement": {"next_wealth": {"labor_income": 0.0}},
    }
