"""Deterministic base model — thin wrapper around lcm_examples.mortality."""

from lcm_examples.mortality import (
    CONSUMPTION_GRID,
    WEALTH_GRID,
    LaborSupply,
    RegimeId,
    borrowing_constraint,
    dead,
    get_model,
    get_params,
    is_working,
    labor_income,
    next_regime_from_retirement,
    next_regime_from_working,
    next_wealth,
    retirement,
    utility_retirement,
    utility_working,
    working_life,
)

__all__ = [
    "CONSUMPTION_GRID",
    "WEALTH_GRID",
    "LaborSupply",
    "RegimeId",
    "borrowing_constraint",
    "dead",
    "get_model",
    "get_params",
    "is_working",
    "labor_income",
    "next_regime_from_retirement",
    "next_regime_from_working",
    "next_wealth",
    "retirement",
    "utility_retirement",
    "utility_working",
    "working_life",
]
