from __future__ import annotations

from collections.abc import Callable
from functools import partial
from typing import TYPE_CHECKING, Literal

import jax
import pandas as pd
from jax import Array

from lcm.input_processing import process_model
from lcm.interfaces import StateActionSpace, StateSpaceInfo
from lcm.logging import get_logger
from lcm.max_Q_over_a import get_argmax_and_max_Q_over_a, get_max_Q_over_a
from lcm.Q_and_F import (
    get_Q_and_F,
)
from lcm.simulation.simulate import simulate
from lcm.solution.solve_brute import solve
from lcm.state_action_space import (
    create_state_action_space,
    create_state_space_info,
)
from lcm.typing import ArgmaxQOverAFunction, ParamsDict

if TYPE_CHECKING:
    from collections.abc import Callable

    import pandas as pd

    from lcm.typing import (
        ArgmaxQOverAFunction,
        MaxQOverAFunction,
        ParamsDict,
    )
    from lcm.user_model import Model


def get_lcm_function(
    model: Model,
    *,
    targets: Literal["solve", "simulate", "solve_and_simulate"],
    debug_mode: bool = True,
    jit: bool = True,  # Ignored - always JIT now since controlled by model.enable_jit
) -> tuple[Callable[..., dict[int, Array] | pd.DataFrame], ParamsDict]:
    """Entry point for users to get high level functions generated by lcm.

    .. deprecated:: 
        This function is deprecated. Use Model.solve(), Model.simulate(), 
        or Model.solve_and_simulate() methods directly instead.

    Return the function to solve and/or simulate a model along with a template for the
    parameters.

    Advanced users might want to use lower level functions instead, but can read the
    source code of this function to see how the lower level components are meant to be
    used.

    Args:
        model: User model specification.
        targets: The requested function types. Currently only "solve", "simulate" and
            "solve_and_simulate" are supported.
        debug_mode: Whether to log debug messages.
        jit: Whether to jit the internal functions. Ignored - JIT is now controlled
            by model.enable_jit parameter.

    Returns:
        - A function that can be used to solve and/or simulate the model (see below).
        - A dictionary with the parameters that the function expects.

        For targets = "solve":
        ----------------------
        A function that takes params and returns the solution of the model, that is, a
        dictionary mapping model period to the respective value function array.

        For targets = "simulate":
        -------------------------
        A function that takes params, a dictionary of initial states, and a model
        solution in form of a value function array, and returns the simulated
        trajectories in a pandas DataFrame, where the multi-index is the combination of
        period and initial-state-ID, and the columns are the optimal actions.

        For targets = "solve_and_simulate":
        -----------------------------------
        The same as targets = "simulate", but with the solution step partialled in, such
        that the function does not require the solution as an argument.

    """
    import warnings
    from functools import partial
    
    warnings.warn(
        "get_lcm_function() is deprecated. Use Model.solve(), Model.simulate(), "
        "or Model.solve_and_simulate() methods directly instead.",
        DeprecationWarning,
        stacklevel=2
    )
    
    if targets not in {"solve", "simulate", "solve_and_simulate"}:
        raise NotImplementedError(f"Target '{targets}' not supported")
    
    if targets == "solve":
        return partial(model.solve, debug_mode=debug_mode), model.params_template
    elif targets == "simulate":  
        return partial(model.simulate, debug_mode=debug_mode), model.params_template
    elif targets == "solve_and_simulate":
        return partial(model.solve_and_simulate, debug_mode=debug_mode), model.params_template


LastPeriodsNextStateSpaceInfo = StateSpaceInfo(
    states_names=(),
    discrete_states={},
    continuous_states={},
)
