"""DC-EGM with generalized resources containing a flat region (means test).

A means-tested floor `R = max(wealth, floor)` makes resources locally flat in
wealth: the composed Euler factor $\\partial R'/\\partial A$ is exactly zero
for savings whose next wealth lands below the floor, so saving into the flat
region has no marginal value. This exercises three pieces of the DC-EGM
kernel at once:

- the composed-gradient factor (zero in the flat region, one above it),
- the degenerate-inversion guard (nodes with all child mass in the flat
  region invert a clamped epsilon instead of zero),
- the upper-envelope cleanup of the candidate structure generated by the
  resulting kink in the marginal continuation.

The integration oracle is a dense-grid brute-force solve of an equivalent
spec; the consume-everything corner case has a closed-form solution.
"""

import functools

import jax.numpy as jnp
import numpy as np

from _lcm.egm.upper_envelope.fues import refine_envelope
from lcm import AgeGrid, IrregSpacedGrid, LinSpacedGrid, Model
from lcm.regime import Regime as UserRegime
from lcm.solvers import DCEGM
from lcm.typing import BoolND, ContinuousAction, ContinuousState, FloatND
from lcm_examples.iskhakov_et_al_2017 import dead
from tests.test_models.deterministic.retirement_only import (
    RetirementOnlyRegimeId,
    next_regime_from_retirement,
)

# Number of model periods; the last one is spent in the terminal `dead` regime.
N_PERIODS = 4

# Means-tested resource floor of the integration model: with pension income
# 10 and zero interest, savings below 20 land next wealth below the floor.
RESOURCES_FLOOR = 30.0

# Floor of the corner-case model, above the entire wealth and savings range,
# so every savings node has all child mass in the flat region.
HIGH_FLOOR = 100.0

WEALTH_GRID = LinSpacedGrid(start=1.0, stop=100.0, n_points=80)
CONSUMPTION_GRID = LinSpacedGrid(start=0.25, stop=100.0, n_points=400)

# Exogenous end-of-period savings grid, cubically clustered toward the
# borrowing limit where the value function curves hardest.
SAVINGS_GRID = IrregSpacedGrid(points=tuple(100.0 * (i / 149) ** 3 for i in range(150)))

CORNER_WEALTH_GRID = LinSpacedGrid(start=1.0, stop=50.0, n_points=40)
CORNER_CONSUMPTION_GRID = LinSpacedGrid(start=0.25, stop=100.0, n_points=200)
CORNER_SAVINGS_GRID = LinSpacedGrid(start=0.0, stop=50.0, n_points=80)


def utility(consumption: ContinuousAction) -> FloatND:
    return jnp.log(consumption)


def resources_with_floor(wealth: ContinuousState) -> FloatND:
    return jnp.maximum(wealth, RESOURCES_FLOOR)


def resources_with_high_floor(wealth: ContinuousState) -> FloatND:
    return jnp.maximum(wealth, HIGH_FLOOR)


def savings(resources: FloatND, consumption: ContinuousAction) -> FloatND:
    return resources - consumption


def inverse_marginal_utility(marginal_continuation: FloatND) -> FloatND:
    return 1.0 / marginal_continuation


def next_wealth_from_savings(
    savings: FloatND, interest_rate: float, pension: float
) -> ContinuousState:
    return (1 + interest_rate) * savings + pension


def next_wealth_brute(
    resources: FloatND,
    consumption: ContinuousAction,
    interest_rate: float,
    pension: float,
) -> ContinuousState:
    return (1 + interest_rate) * (resources - consumption) + pension


def budget_constraint(consumption: ContinuousAction, resources: FloatND) -> BoolND:
    return consumption <= resources


@functools.cache
def _get_means_tested_model(variant: str) -> Model:
    """Build the means-tested model for one solver variant (`dcegm`/`brute`)."""
    ages = AgeGrid(start=40, stop=40 + (N_PERIODS - 1) * 10, step="10Y")
    last_age = ages.exact_values[-1]
    common = {
        "transition": next_regime_from_retirement,
        "active": lambda age, la=last_age: age < la,
        "actions": {"consumption": CONSUMPTION_GRID},
        "states": {"wealth": WEALTH_GRID},
    }
    if variant == "brute":
        regime = UserRegime(
            **common,
            state_transitions={"wealth": next_wealth_brute},
            constraints={"budget_constraint": budget_constraint},
            functions={"utility": utility, "resources": resources_with_floor},
        )
    else:
        regime = UserRegime(
            **common,
            state_transitions={"wealth": next_wealth_from_savings},
            functions={
                "utility": utility,
                "resources": resources_with_floor,
                "savings": savings,
                "inverse_marginal_utility": inverse_marginal_utility,
            },
            solver=DCEGM(
                continuous_state="wealth",
                continuous_action="consumption",
                resources="resources",
                post_decision_function="savings",
                savings_grid=SAVINGS_GRID,
                n_constrained_points=64,
            ),
        )
    return Model(
        regimes={"retirement": regime, "dead": dead},
        ages=ages,
        regime_id_class=RetirementOnlyRegimeId,
    )


@functools.cache
def _get_corner_model() -> Model:
    """Build the consume-everything corner model.

    The floor exceeds the whole savings range, so the child's resources are
    constant and the expected marginal continuation is exactly zero at every
    savings node — the degenerate-inversion guard must carry the entire
    solution through the constrained segment.
    """
    ages = AgeGrid(start=40, stop=40 + (N_PERIODS - 1) * 10, step="10Y")
    last_age = ages.exact_values[-1]
    regime = UserRegime(
        transition=next_regime_from_retirement,
        active=lambda age, la=last_age: age < la,
        actions={"consumption": CORNER_CONSUMPTION_GRID},
        states={"wealth": CORNER_WEALTH_GRID},
        state_transitions={"wealth": next_wealth_from_savings},
        functions={
            "utility": utility,
            "resources": resources_with_high_floor,
            "savings": savings,
            "inverse_marginal_utility": inverse_marginal_utility,
        },
        solver=DCEGM(
            continuous_state="wealth",
            continuous_action="consumption",
            resources="resources",
            post_decision_function="savings",
            savings_grid=CORNER_SAVINGS_GRID,
            n_constrained_points=64,
        ),
    )
    return Model(
        regimes={"retirement": regime, "dead": dead},
        ages=ages,
        regime_id_class=RetirementOnlyRegimeId,
    )


def _get_params(*, pension: float) -> dict:
    final_age_alive = 40 + (N_PERIODS - 2) * 10
    return {
        "discount_factor": 0.95,
        "interest_rate": 0.0,
        "final_age_alive": final_age_alive,
        "retirement": {"next_wealth": {"pension": pension}},
    }


def test_means_tested_transfer_matches_dense_brute_force():
    """DC-EGM with a flat-resources region matches dense brute force.

    The floor binds on the lower part of the wealth grid (resources are
    constant there, so V must be flat in wealth below the floor) and the
    zero-marginal flat region generates the candidate structure the upper
    envelope cleans. Tolerance: the brute solver carries its consumption-grid
    quantization and V-interpolation error; with the floor, resources never
    fall below 30, so even the lowest wealth nodes are brute-stable and the
    comparison runs on the full grid.
    """
    params = _get_params(pension=10.0)
    dcegm_solution = _get_means_tested_model("dcegm").solve(
        params=params, log_level="debug"
    )
    brute_solution = _get_means_tested_model("brute").solve(
        params=params, log_level="debug"
    )

    for period in sorted(brute_solution)[:-1]:
        np.testing.assert_allclose(
            np.asarray(dcegm_solution[period]["retirement"]),
            np.asarray(brute_solution[period]["retirement"]),
            atol=1e-2,
            rtol=1e-3,
            err_msg=f"period={period}",
        )


def test_all_child_mass_in_flat_region_yields_consume_everything():
    """With the floor above the savings range, consuming everything is optimal.

    Saving has exactly zero marginal value (the child's resources are pinned
    at the floor), so the degenerate-inversion guard must produce the corner:
    consume all resources, leaving the closed-form value
    $V_t = \\sum_k \\beta^k \\log(\\text{floor})$ at every wealth node. The
    solve must stay finite throughout (`log_level="debug"` raises on NaN).
    Tolerance: the queried resources value coincides with the top constrained
    candidate up to the float residue of the geometric candidate spacing.
    """
    params = _get_params(pension=0.0)
    solution = _get_corner_model().solve(params=params, log_level="debug")

    discount_factor = 0.95
    decision_periods = sorted(solution)[:-1]
    for period in decision_periods:
        V_arr = np.asarray(solution[period]["retirement"])
        assert np.all(np.isfinite(V_arr)), f"period={period}"
        n_remaining = len(decision_periods) - period
        expected = np.log(HIGH_FLOOR) * sum(
            discount_factor**k for k in range(n_remaining)
        )
        np.testing.assert_allclose(
            V_arr,
            np.full_like(V_arr, expected),
            atol=1e-6,
            rtol=1e-9,
            err_msg=f"period={period}",
        )


def _flat_region_kink_candidates():
    """Candidates from a means-test kink in the marginal continuation.

    Two choice-specific segments as the Euler inversion produces them around
    the floor exit:

    - Segment L (consume everything out of the flat region): saving stays at
      the borrowing limit, so the policy is `c = R` (implied savings 0) and
      the value line is `v = 2.0 + 0.5 R`, sampled at R in {0.5, 1.4, 2.3,
      4.1}.
    - Segment H (save past the floor threshold): `c = 0.25 R` (implied
      savings `0.75 R`) with the steeper value line `v = 0.2 + 1.1 R`,
      sampled at R in {1.0, 2.0, 3.4, 4.4}.

    The lines cross at R* = 3.0 (v = 3.5): the envelope is L below, H above,
    with a policy discontinuity from 3.0 down to 0.75 at the kink.
    """
    r_flat = np.array([0.5, 1.4, 2.3, 4.1])
    r_saver = np.array([1.0, 2.0, 3.4, 4.4])
    grid = np.concatenate([r_flat, r_saver])
    value = np.concatenate([2.0 + 0.5 * r_flat, 0.2 + 1.1 * r_saver])
    policy = np.concatenate([r_flat, 0.25 * r_saver])
    return jnp.asarray(grid), jnp.asarray(policy), jnp.asarray(value)


# Analytic crossing of the two value lines in `_flat_region_kink_candidates`.
R_STAR = 3.0
V_STAR = 2.0 + 0.5 * R_STAR


def test_fues_cleans_flat_resources_continuation_kink():
    """FUES keeps the analytic envelope of the flat-region/saver candidates.

    Dominated points of each branch are removed, the segment crossing is
    inserted twice (left policy `c = R*`, right policy `c = 0.25 R*`), and
    the refined arrays represent `max` of the two value lines under linear
    interpolation.
    """
    grid, policy, value = _flat_region_kink_candidates()

    refined_grid, refined_policy, refined_value, n_kept = refine_envelope(
        endog_grid=grid, policy=policy, value=value, n_refined=16
    )

    assert int(n_kept) == 7
    kept = ~np.isnan(np.asarray(refined_grid))
    got_grid = np.asarray(refined_grid)[kept]
    got_policy = np.asarray(refined_policy)[kept]
    got_value = np.asarray(refined_value)[kept]
    np.testing.assert_allclose(
        got_grid, [0.5, 1.4, 2.3, R_STAR, R_STAR, 3.4, 4.4], atol=1e-8
    )

    kink_slots = np.isclose(got_grid, R_STAR)
    np.testing.assert_allclose(got_policy[kink_slots], [R_STAR, 0.25 * R_STAR])
    np.testing.assert_allclose(got_value[kink_slots], [V_STAR, V_STAR], atol=1e-8)

    queries = np.array([0.7, 1.5, 2.5, 2.9, 3.1, 4.0, 4.3])
    analytic = np.maximum(2.0 + 0.5 * queries, 0.2 + 1.1 * queries)
    np.testing.assert_allclose(
        np.interp(queries, got_grid, got_value), analytic, atol=1e-8
    )
